### ISSUE TITLE
"Group DataSets" only renders one of the group's data sets

### ISSUE THREAD

**Issue by ingowald** [TACC/pvOSPRay#2]
As originally reported by R.Pichler on the ospray mailing list:
(moved from ospray mailing list to pvospray issues by iw)

Hi,

I built pvOSPRay for ParaView 4.3 and I can go through the two demos on
the page http://tacc.github.io/pvOSPRay/demos.html. When I tried to
apply it to my data I didn't work as soon as I used group datasets.
Hence, I was wondering if something is wrong with my build or if this
feature is not implemented. Based on the "Basic Walk-Trough" I can see
the same problem if I create two Wavelet sources and place them next to
each other. Then I apply group datasets and create a contour as in the
demo and only the contour in one of the wavelets is rendered. The same
procedure works fine using the standard Render View. Did anyone
experience something similar and find a workaround?

**Comment by carsonbrownlee** [comment]
I believe I fixed this under my limited testing.
