### ISSUE TITLE
OSPRay Preferences don't appear on Mac (ParaView)

### ISSUE THREAD

**Issue by lyon-fnal** [TACC/pvOSPRay#26]
I got pvOSPRay to build on the Mac with ParaView 4.4 (with the 4.4 branch of ovOSPRay and the devel branch of OSPRay). Things seem to work except that the OSPRay preferences do not appear in the preferences window. For example,

![image](https://cloud.githubusercontent.com/assets/9458395/10838806/b29674de-7e99-11e5-8f75-6d964fbbbbe8.png)

Any ideas? Thanks!

**Comment by carsonbrownlee** [comment]
hello,
sorry for my late reply.  If you are following the tutorials, ParaView 4.3.x+ changed the settings a bit.  Options for the number of samples, etc. now show up in the same place as materials, colors, etc. in the lower left.  This is actually a "bug" in a sense, but fortunately they can still be used there.

**Comment by lyon-fnal** [comment]
Ah - ok. Indeed I was following the tutorial. It's not a bug if those
options are still there!  Thanks for the reply! --Adam

_------_

_Adam L. Lyon_
_Scientist; Associate Division Head for Systems for Scientific Applications_

Scientific Computing Division & Muon g-2 Experiment
Fermi National Accelerator Laboratory
630 840 5522 office
www.fnal.gov
lyon@fnal.gov

Connect with us!
Newsletter http://www.fnal.gov/pub/today/  |  Facebook
https://www.facebook.com/Fermilab  |  Twitter
https://twitter.com/Fermilab

**Comment by carsonbrownlee** [comment]
and thanks for the feedback!
Carson

On Nov 2, 2015, at 12:41 PM, Adam Lyon <notifications@github.com<mailto:notifications@github.com>> wrote:

Ah - ok. Indeed I was following the tutorial. It's not a bug if those
options are still there! Thanks for the reply! --Adam

_------_

_Adam L. Lyon_
_Scientist; Associate Division Head for Systems for Scientific Applications_

Scientific Computing Division & Muon g-2 Experiment
Fermi National Accelerator Laboratory
630 840 5522 office
www.fnal.govhttp://www.fnal.gov
lyon@fnal.govmailto:lyon@fnal.gov

Connect with us!
Newsletter http://www.fnal.gov/pub/today/ | Facebook
https://www.facebook.com/Fermilab | Twitter
https://twitter.com/Fermilab
