### ISSUE TITLE
documentation error

### ISSUE THREAD

**Issue by ingowald** [TACC/pvOSPRay#4]
Under 'building', it says:

 cd /Plugins 

should this be "cd ParaView-v4.1.0/Plugins" ?

Also, what is "cd paraview_build_dir"? Do I have to first create this directory? If so, should I place that into the Plugins dir?

**Comment by carsonbrownlee** [comment]
Paul?  It looks like the README.md directions haven’t been updated to match the github.io documentation for 4.3.
Carson

**Comment by pnav** [comment]
Huh, thought I did that, but I guess not. I’ll check. Of course, we could just have the README.md say ‘look at the website’ :-)

On Jul 17, 2015, at 12:20 PM, carsonbrownlee <notifications@github.com<mailto:notifications@github.com>> wrote:

Paul? It looks like the README.md directions haven’t been updated to match the github.io documentation for 4.3.
Carson

**Comment by carsonbrownlee** [comment]
That would likely be better, no sense duplicating things.
Carson

**Comment by pnav** [comment]
updated this to point to the github pages build instructions
